---
- name: Template profile and service file
  ansible.builtin.template:
    src: "create-app/index.html.j2"
    dest: "{{ coolify_app_volume }}/"
    owner: "{{ coolify_user }}"
    group: "{{ coolify_user }}"
    mode: 0640

- name: Create app from manifest
  command:
    cdir: "{{ coolify_app_volume }}/create-app/"
    cmd: python -m http.server &>/dev/null

- name: Finalize app
  uri:
    url: "{{ github_api }}/app-manifests/{{ gh_app_form_res.code }}/conversions"
    headers:
      Authorization: " token {{ coolify_github_api_token }}"
      Accept: "application/vnd.github.v3+json"
    body_format: json,
    status_code: 201, 422
  register: gh_app_infos_res

- set_fact:
    _coolify_env: "{{
      {
        VITE_GITHUB_APP_NAME: gh_app_infos_res.name,
        VITE_GITHUB_APP_CLIENTID: gh_app_infos_res.client_id,
        GITHUB_APP_CLIENT_SECRET: gh_app_infos_res.client_secret,
        GITHUP_APP_WEBHOOK_SECRET: gh_app_infos_res.webhook_secret,
        GITHUB_APP_PRIVATE_KEY: gh_app_infos_res.pem
      } | combine(_coolify_env)
    }}"
  when: "'client_id' in gh_app_infos_res"
