- name: "Clone repo"
  become: true
  ansible.builtin.git:
    repo: 'https://{{ coolify_git_provider }}/{{ coolify_git_org }}/{{ coolify_git_repo }}.git'
    dest: "{{ coolify_app_volume }}"
    version: "{{ coolify_version | d('main') }}"
    force: True

- name: "Create install folders"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  become: yes
  loop:
    - "{{ coolify_data_volume }}"
    - "{{ coolify_app_volume }}"

- name: Template profile and service file
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: .env.j2, dest: "{{ coolify_data_volume }}/.env" }
    - { src: coolify.service.j2, dest: "/etc/systemd/system/coolify.service" }
    - { src: install.sh.j2, dest: "{{ coolify_data_volume }}/install.sh" }

- name: "Rights exe"
  ansible.builtin.file:
    path: "{{ coolify_app_volume }}/install.sh"
    state: file
    owner: "{{ coolify_user }}"
    group: "{{ coolify_user }}"
    mode: 0550
  become: yes

- name: Install
  become: True
  ansible.builtin.command:
    chdir: "{{ coolify_data_volume }}"
    cmd: "./install.sh {{ coolify_install_mode }}"
  notify:
    - reload systemd
    - restart coolify

- name: Enable coolify
  ansible.builtin.systemd:
    name: coolify
    enabled: True
  become: True
