---
- name: "Clone repo"
  ansible.builtin.git:
    repo: 'https://{{ coolify_git_provider }}/{{ coolify_git_org }}/{{ coolify_git_repo }}.git'
    dest: "{{ coolify_app_volume }}"
    version: "{{ coolify_version }}"
    force: "{{ coolify_force_update }}"
  ignore_errors: "{{ coolify_force_update == False }}"
  register: coolify_version_state

- name: "Create install folders"
  become: True
  become_user: root
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ coolify_user }}"
    group: "{{ coolify_user }}"
    mode: 0755
  loop:
    - "{{ coolify_data_volume }}"
    - "{{ coolify_data_volume_mongo }}"
    - "{{ coolify_app_dir }}"
    - "{{ coolify_app_volume }}"

- name: Template profile and service file
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ coolify_user }}"
    group: "{{ coolify_user }}"
    mode: 0640
  loop:
    - { src: .env.j2, dest: "{{ coolify_app_volume }}/.env" }
    - { src: install.sh.j2, dest: "{{ coolify_data_volume }}/install.sh" }
    - { src: Dockerfile, dest: "{{ coolify_data_volume }}/Dockerfile" }
    - { src: docker-compose.yml.j2, dest: "{{ coolify_data_volume }}/docker-compose.yml" }

- name: "Rights exe"
  ansible.builtin.file:
    path: "{{ coolify_data_volume }}/install.sh"
    state: file
    owner: "{{ coolify_user }}"
    group: "{{ coolify_user }}"
    mode: 0550
  become: yes

- name: Deploy swarm stack
  ansible.builtin.command:
    chdir: "{{ coolify_data_volume }}"
    cmd: "./install.sh {{ coolify_install_mode }}"

- name: "Delete env file"
  ansible.builtin.file:
    path: "{{ coolify_app_volume }}/.env"
    state: absent
  become: yes
